[theme]
primaryColor = "#080536"              # Purple-ish buttons, highlights
backgroundColor = "#5a6a7c"           # Light gray background
secondaryBackgroundColor = "#031224"  # Slightly darker gray for cards/sections
textColor = "#ffffff"                  # Dark text
font = "sans serif"                    # Modern readable font