[theme]
primaryColor = "#6C63FF"              # Purple-ish buttons, highlights
backgroundColor = "#081735"           # Light gray background
secondaryBackgroundColor = "#E0E0E0"  # Slightly darker gray for cards/sections
textColor = "#ffffff"                  # Dark text
font = "sans serif"                    # Modern readable font